#!/usr/bin/env bash
CC=gcc
CFLAGS=-Wall -Werror -Wextra -pedantic
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME=school

.PHONY: all clean oclean fclean re

all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

clean:
	$(RM) -f *~ *.swp $(NAME)

oclean:
	$(RM) -f $(OBJ)

fclean: clean oclean

re: oclean $(OBJ) all
