#!/usr/bin/env bash
CC=gcc
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME=school
RM=rm

all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

clean:
	$(RM) -f *~ *.swp $(NAME)

oclean:
	$(RM) -f $(OBJ)

fclean:
	$(RM) -f *~ *.swp $(NAME)
	$(RM) -f $(OBJ)

re: oclean $(OBJ) all
