#!/usr/bin/env bash
CC=gcc
SRC = main.c school.c
OBJ = $(SRC:.c=.o)
NAME=school
RM=rm

all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

clean:
	$(RM) *# *.swp $(NAME)

oclean:
	$(RM) *.o

fclean:
	$(RM) *.o *# *.swp $(NAME)

re: $(OBJ)
	$(CC) $(SRC) -o $(NAME)
