#!/usr/bin/env bash
CC=gcc
SRC = main.c school.c
OBJ := $(SRC:.c=.o)
NAME=school
RM=rm
OBJ_COPY=$(OBJ)

all: $(OBJ)
	$(CC) $(OBJ) -o $(NAME)

clean:
	$(RM) -f *~ $(NAME)

oclean:
	$(RM) -f $(OBJ)

fclean:
	$(RM) -f *~ $(NAME)
	$(RM) -f $(OBJ)

re: $(OBJ_COPY)
	$(RM) -f $(OBJ)
	$(CC) $(OBJ) -o $(NAME)
